import React from "react";

const Privacy = () => {
  return (
    <div className="flex items-center justify-center py-10 ">
      <div className="w-[80%] ">
        <h1 className="text-4xl">Privacy Policy</h1>
        <h2 className="text-2xl font-semibold">Last updated: June 27, 2023</h2>
        <p>
          This Privacy Policy outlines the practices and procedures of SSaver
          regarding the collection, use, and disclosure of your information when
          you use our service. It also explains your privacy rights and the
          legal protections in place.
        </p>
        <p>
          By using our service, you agree to the collection and use of your
          information as described in this Privacy Policy.
        </p>
        <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
        <h3 className="text-xl font-semibold">Interpretation</h3>
        <p>
          Terms with capitalized initials have defined meanings specified under
          certain conditions. These definitions hold the same meaning regardless
          of whether they are singular or plural.
        </p>
        <h3 className="text-xl font-semibold">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <p>
          Business refers to the legal entity, SSaver, that collects consumers
          personal information and determines the purposes and means of
          processing such information.
        </p>
        <p>
          Company refers to SSaver, located in Nigeria,  and may be
          referred to as We, Us, or Our in this Policy. The Company is the
          Data Controller under the relevant regulations.
        </p>
        <p>
          Consumer refers to a natural person who is a resident of California
          and is the subject of personal information collected by the Company.
          Cookies are small files containing browsing history details that are
          placed on your device by a website.
        </p>
        <p>Country refers to Nigeria, Africa.</p>
        <p>
          Data Controller refers to the Company as the legal entity that
          determines the purposes and means of processing personal data. Device
          means any device, such as a computer, cellphone, or tablet, that can
          access the service.
        </p>
        <p>
          Do Not Track (DNT) is a concept promoted by regulatory authorities for
          allowing users to control online tracking.
        </p>
        <p>
          Personal Data refers to any information related to an identified or
          identifiable individual, as defined under applicable regulations. Sale
          refers to the transfer of a consumers personal information to another
          business or third party for valuable consideration. Service refers to
          the website, SSaver.
        </p>
        <p>
          Service Provider refers to third-party companies or individuals
          employed by the Company to facilitate and provide the Service, as well
          as analyze its usage. Third-party Social Media Service refers to any
          website or social network through which users can log in or create
          accounts to use the Service. Usage Data refers to data collected
          automatically, either generated by the use of the Service or from the
          Service infrastructure itself (e.g., page visit duration). Website
          refers to SSaver.
        </p>
        <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-semibold">Types of Data Collected</h3>
        <h3 className="text-xl font-semibold">Personal Data</h3>
        <p>
          When using our service, we may ask you to provide certain personally
          identifiable information that can be used to contact or identify you.
          This may include, but is not limited to:
        </p>
        <p>Email address First, name and last name, Usage Data</p>
        <h3 className="text-xl font-semibold">Usage Data</h3>
        <p>
          We collect Usage Data automatically when you use our service. Usage
          Data may include information such as your Devices Internet Protocol
          (IP) address, browser type, browser version, the pages of our Service
          that you visit, the time and date of your visit, the time spent on
          those pages, unique device identifiers, and other diagnostic data.
          When you access the service through a mobile device, we may collect
          certain information automatically, including, but not limited to, the
          type of mobile device you use, your mobile devices unique ID, the IP
          address of your mobile device, your mobile operating system, the type
          of mobile Internet browser you use, unique device identifiers, and
          other diagnostic data. We may also collect information that your
          browser sends whenever you visit our Service or when you access the
          service through a mobile device.
        </p>
        <p>
          We take reasonable precautions to ensure that your personal
          information is treated securely and in accordance with this Privacy
          Policy. However, no data transmission or storage system can be
          guaranteed to be 100% secure. If you have reason to believe that your
          interaction with us is no longer secure, please contact us
          immediately.
        </p>
        <h3 className="text-xl font-semibold">Retention of Your Personal Data</h3>
        <p>
          We will retain your personal data only for as long as it is necessary
          for the purposes stated in this Privacy Policy. We will also retain
          and use your personal data to the extent necessary to comply with our
          legal obligations, resolve disputes, and enforce our legal agreements
          and policies.
        </p>
        <h3>Changes to This Privacy Policy</h3>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page and
          updating the Last updated date at the top of the policy. It is
          recommended that you review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <h3 className="text-xl font-semibold">Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, please contact
          us:
        </p>
        <p>
          By visiting our website:{" "}
          <a className="text-blue-500" href="/contact"> https://ssaver.com/contact</a>
        </p>
        <p>
          Thank you for taking the time to read our Privacy Policy. We value and
          respect your privacy.
        </p>
      </div>
    </div>
  );
};

export default Privacy;
